execute @e[type=addon:g9] ~ ~ ~ summon vehicle:ah1sr ~~~ monster
execute @e[type=addon:g10] ~ ~ ~ summon vehicle:ah1sr ~~~ player
execute @e[type=addon:g15] ~ ~ ~ summon vehicle:t34 ~~~
execute @e[type=addon:g15] ~ ~ ~ summon addon:ga ~~~
execute @e[type=addon:g11] ~ ~ ~ summon vehicle:m41 ~~~
execute @e[type=addon:g11] ~ ~ ~ summon addon:ca ~~~
execute @e[type=addon:g12] ~ ~ ~ summon vehicle:t72 ~~~
execute @e[type=addon:g12] ~ ~ ~ summon addon:ga ~~~
execute @e[type=addon:g13] ~ ~ ~ summon vehicle:m60 ~~~
execute @e[type=addon:g13] ~ ~ ~ summon addon:ca ~~~
execute @e[type=addon:g14] ~ ~ ~ summon vehicle:pt76 ~~~
execute @e[type=addon:g14] ~ ~ ~ summon addon:ga ~~~
kill @e[type=addon:g9]
kill @e[type=addon:g10]
kill @e[type=addon:g11]
kill @e[type=addon:g12]
kill @e[type=addon:g13]
kill @e[type=addon:g14]
kill @e[type=addon:g15]